### ISSUE TITLE
机器人登录时获取机器人二维码存在问题

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#102]
Hi:
   我在机器人登录成功后，获取机器人的二维码信息时，获取到以下情况：

![image](https://user-images.githubusercontent.com/16509241/42806428-020374f4-89e1-11e8-93ce-8c135414cee7.png)

通过查看源码发现返回的内容是 result.data， result中并没有data这个key, 麻烦确认下是否存在问题。
![image](https://user-images.githubusercontent.com/16509241/42806488-2a60f07a-89e1-11e8-88be-1c4ee3823694.png)

**Comment by lijiarui** [comment]
This is a confirmed bug because this function hasn't been implemented yet.

We will implement this these days
