### ISSUE TITLE
群里面@某人发送消息的时候，只有一个@符号，没有昵称

### ISSUE THREAD

**Issue by 123cbfds** [lijiarui/wechaty-puppet-padchat#105]
使用 bot.Contact.load(wxid)，获取 Contact ，room.say(m, contactList) 这个时候消息里面只有 @ 符号 + 消息内容

**Comment by lijiarui** [comment]
@123cbfds Please give the reproduce code and related log, thanks ：）

**Comment by zhoumh1988** [comment]
说明群里没有找到这个人

**Comment by lijiarui** [comment]
@123cbfds Have you fix this yet?

**Comment by windmemory** [comment]
This is related to issues about mention feature, merge to https://github.com/lijiarui/wechaty-puppet-padchat/issues/104
