### ISSUE TITLE
获取群的正确操作姿势？

### ISSUE THREAD

**Issue by JinksPeng** [lijiarui/wechaty-puppet-padchat#108]
关于  `bot.room.findAll()` 返回群遗漏； 
这是与微信获取群的机制有关，目前如何操作能尽可能获取? 延迟一段时间好像还是不够

**Comment by JinksPeng** [comment]
如果是之前获取的群一次能获取，新增的群至少需要等几分钟

**Comment by lijiarui** [comment]
你可以设置两次，看两次findAll 的结果进行对比，如果数量一样，那么大概率就是没有遗漏了。

**Comment by windmemory** [comment]
@JinksPeng 您能再具体点描述下您的情况么？

* 您是在什么情况下获取这个新群的信息呢？是刚刚启动wechaty还是说启动了一段时间之后。如果是启动一段时间之后，大概过了多久呢？
* 这个新群是什么时候建立的呢？是在wechaty启动之前，还是在wechaty启动之后？

麻烦您提供一下完整的操作时间顺序，这样更有利于我们来debug这个问题，谢谢啦

**Comment by JinksPeng** [comment]
@windmemory 

1. 当一个新号扫码登陆的时候，findAll() 第一次返回0-2个，大概1分钟后再返回1-2个, 之后1分钟后再返回1-2个, 以此类推, (有的号可能到某个时间之后就不再返回新的群);

2. 如果是一个之前登陆过的用户，findAll()能返回之前已经返回的所有群，但微信上新增的群，也是需要1分钟左右才会返回; 如果是重命名，则能马上返回;

**Comment by windmemory** [comment]
@JinksPeng 
谢谢您提供的细节信息。
根据您的问题，我写了一页简单的wiki来讲我们这边contact load的一些细节，在[这里](https://github.com/lijiarui/wechaty-puppet-padchat/wiki/Padchat-%E9%80%9A%E8%AE%AF%E5%BD%95%E5%8A%A0%E8%BD%BD%E8%AF%A6%E8%A7%A3)

然后第二个问题，有一些群建立之后，如果没有人说话的话，其他的人好像是看不到这个群的。至少目前我从手机上的微信是看到了这样的情况。那么如果正常微信上面无法得知新建的群聊的话，我们这边也是对此无能为力的。

想麻烦您再确认一下，您微信上新增的群，建立之后有没有立刻说话，如果没有的话，请尝试一下立刻在群里说句话，然后再看看这个群是不是能加载出来。如果这样还是不行的，请麻烦您帮我们开另外一个单独的issue，我们好来track这个问题

**Comment by windmemory** [comment]
@JinksPeng 请问这个问题还存在么？如果还存在请回复这个issue和我们沟通一下，如果您两天之内还没有回复的话，我们就先把这个issue关闭了

**Comment by windmemory** [comment]
关闭这个issue，如果有问题的话请reopen :)
