### ISSUE TITLE
服务出现initWebSocket() ws.on(close) 1006 错误后，服务再无法收到消息、踢人、拉人等对应的事件消息

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#109]
![7321532077084_ pic_hd](https://user-images.githubusercontent.com/16509241/42996417-0dc140e8-8c46-11e8-8602-4cb34ae3a977.jpg)

**Comment by windmemory** [comment]
@zhaokefei 能麻烦再确认一下，这个问题对于`v0.9.9`是否还在继续出现了么？如果没有的话，麻烦帮忙关闭这个issue吧
