### ISSUE TITLE
无法获取调用room.say() 或 contact.say() 后的消息ID

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#112]
**由于调用 say() 方法发送的消息，不会再次触发 message 这个event，所有无法拿到消息ID**

需要拿到该消息ID的原因：如果群内有多个机器人时，可以根据消息ID来判断是不是同一条消息，可以保证只往上游服务一个群内同一条消息只发送一次，但是调用的say方法发送的消息无法拿到消息ID，这时候就无法保证消息往上游只推送一次。

**Comment by windmemory** [comment]
This is a change involve `wechaty` project, so move to another repository. 

https://github.com/Chatie/wechaty/issues/1501
