### ISSUE TITLE
An error occurred while logout

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#118]
When I logout WeChat, the following error will be reported, causing the logout event to fail to trigger.

**Manual WeChat Logout**

![image](https://user-images.githubusercontent.com/16509241/43191122-1ad08038-902d-11e8-8d36-60933c4e1d2e.png)

**Call Logout Api**

![image](https://user-images.githubusercontent.com/16509241/43191137-214eef1c-902d-11e8-9743-0443aee385c2.png)

**Comment by windmemory** [comment]
I submitted a small fix to improve the `logout` logic, please verify this issue still happened for the new version `v0.9.27`. If not, please close this issue :)
