### ISSUE TITLE
An error occurred while running the wechaty instance （about room-invitation）

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#120]
**When I start a wechaty instance, the following error occurs：**
**My code is：**
![image](https://user-images.githubusercontent.com/16509241/43245822-3cd6d794-90e2-11e8-874d-f749b3cfc358.png)
![image](https://user-images.githubusercontent.com/16509241/43245853-57d62676-90e2-11e8-85c6-c4a0b77b2a37.png)

**pachat version is 0.9.0**

![image](https://user-images.githubusercontent.com/16509241/43245764-07467666-90e2-11e8-8c18-21a6aba9fbb2.png)

**Comment by windmemory** [comment]
Should be solved with https://github.com/lijiarui/wechaty-puppet-padchat/commit/af5d0106bbeed25bd3fc6c193b0726294fe84756

@zhaokefei Please help us double check whether the issue is resolved with `v0.9.7`. If so, please close this issue.

**Comment by windmemory** [comment]
Ping @zhaokefei
