### ISSUE TITLE
关于安装的问题，及解决方案

### ISSUE THREAD

**Issue by zmrbak** [lijiarui/wechaty-puppet-padchat#125]
在安装wechaty-puppet-padchat过程中，会遇到node-expat编译的问题，很多新手这里就卡住了，主要是编译环境的配置问题。

其实有更好的解决方案，依次执行如下三条指令即可：

npm install --global --production windows-build-tools
npm install wechaty@next
npm install wechaty-puppet-padchat

当然，如果npm都没有的话，就需要在这之前安装node.js，目前要求为>10的版本。
第一条指令：安装Windows编译工具。
第二条指令：安装最新版本的wechaty
第三条指令：安装wechaty-puppet-padchat

**Comment by lijiarui** [comment]
可以把 `npm install wechaty@next` 换成 `npm install wechaty`

`@next` 代表安装最新版本的wechaty，但是有可能是不稳定版本的。

建议使用 npm install wechaty 安装最新版本稳定的wechaty

**Comment by yph152** [comment]
@lijiarui 麻烦问下，初始化时有个 token 这个具体指的是什么，如何获取到

**Comment by lijiarui** [comment]
@yph152 see [wiki](https://github.com/lijiarui/wechaty-puppet-padchat/wiki/%E8%B4%AD%E4%B9%B0token)

**Comment by windmemory** [comment]
Let's close this issue since no more comments last three weeks. Please reopen this issue if you have more questions.

**Comment by lijiarui** [comment]
@zmrbak Could you add my wechat please? `13141321843`
