### ISSUE TITLE
sync room members always get cache data

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#132]
I use the `room.sync()` method to force update room members when I get member list. but always get cache data, and according to the log information, the following methods seem to be not executed.

![image](https://user-images.githubusercontent.com/16509241/43759559-261fef12-9a52-11e8-9363-47f6ec448e33.png)

![image](https://user-images.githubusercontent.com/16509241/43759574-32af1aa0-9a52-11e8-8332-ecdfb54bbd04.png)

**Comment by windmemory** [comment]
@zhaokefei Could you please try with `wechaty` `v0.19.158` to see if this issue still happens?
If not, please close this issue.

**Comment by windmemory** [comment]
ping @zhaokefei
