### ISSUE TITLE
Use `log.info` only with what you really want user to know

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-puppet-padchat#137]
I suggest that we should change the log level for the following log from `info` to `verb`.

```
17:50:11 INFO PadchatRpc rpcCall(WXGetChatRoomMember) interrupted by connection broken, scheduled this api call. This call will be made again when connection restored
17:50:11 INFO PadchatRpc rpcCall(WXGetContact) interrupted by connection broken, scheduled this api call. This call will be made again when connection restored
```

**Comment by zixia** [comment]
Closed by #138

**Comment by windmemory** [comment]
Thanks for raising this issue and submitting this change. I agree with the suppressing on logs about delayed api calls.

However I would argue about suppressing `reconnect` log from `info` to `verbose`. I think user should be able to know when padchat reconnected. If anything wrong happened, it gives a better clue to the user about what's happening. 

The reconnect has already bypassed the `logout` and `login` event, if there is no log even, user will be confusing when something wrong happened.

**Comment by zixia** [comment]
I published this change is because when I debugging Wechaty under Heroku the module print too many logs at INFO level, which makes me very hard to get the necessary information.

Fortunately, I had just finished the debugging just now. So you can revert the changes if you like.
