### ISSUE TITLE
Can not login via QR Code

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-puppet-padchat#140]
version: ^0.9.12

reproduce:

1. start the bot, get the QR code
1. scan the QR code on the Phone to log in
1. on the phone, at the top of wechat app conversion list, click `iPad 微信已登录`
1. click `退出 iPad 微信` on the phone(wechat app)
1. back to the Wechaty bot, it should display a new QR Code because it was logout-ed
1. scan the new QR Code again, click on the phone again to allow login
1. the Wechaty does not log in at all.

**Comment by windmemory** [comment]
Could you please try to reproduce this issue with latest `wechaty-puppet-padchat`? This issue should be fixed with 711495ab221f719d2429c6f08d135872edc407fd

@zixia

**Comment by zixia** [comment]
Great, will try it when I have time. 

Thanks!

**Comment by zixia** [comment]
I had no time to test it but I'd like to believe it had been resolved.

Close this issue for now.

**Comment by windmemory** [comment]
Thanks for track this
