### ISSUE TITLE
Error: not logged in, no this.id yet

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-puppet-padchat#147]
```
> caiyun-wechaty@0.4.26 start /Users/luomiao/workspace/xiaoyi-bot/caiyun-wechaty
> ts-node src/main.ts

21:40:46 INFO Wechaty <Puppet#0<PuppetPadchat>()/PuppetPadchat#0> start() v0.19.139 is starting...
21:40:46 INFO Hapi listening to http://localhost:8088
21:40:46 ERR CaiYun Error: not logged in, no this.id yet.
21:40:46 INFO AutoReport finis(1, exit)
21:40:46 INFO AutoReport finis() bot had been logout-ed
21:40:46 INFO AutoReport finis() setTimeoutprocess.exit(), 10 * 1000)
21:40:46 INFO AutoReport finis() setTimeout() going to exit with 1
21:40:46 INFO Wechaty <Puppet#0<PuppetPadchat>(wechaty-caiyun-test-1)/PuppetPadchat#0> stop() v0.19.139 is stoping ...
```

It got "Error: not logged in, no this.id yet. " for no reason.

Will get the SILLY log later.

Related to https://github.com/caiyunapp/caiyun-wechaty/issues/8

**Comment by windmemory** [comment]
The link is returning 404, could you please check that?

**Comment by zixia** [comment]
Sorry, that's a private repo that I just linked at here for link them together.

I'll try to reproduce it and get the silly log when I got time.

**Comment by windmemory** [comment]
Is this still reproducible? @zixia

**Comment by zixia** [comment]
It seems this should be related with your PR to Wechaty at <https://github.com/Chatie/wechaty/issues/1549>.

Hope that would fix this by making the error message more clear.

I'll close this issue for now, and reopen it if I meet this problem again.

Thanks for following this!
