### ISSUE TITLE
roomAnnounce() got undefined

### ISSUE THREAD

**Issue by kis87988** [lijiarui/wechaty-puppet-padchat#148]
### Run `npm run doctor` or `wechaty run doctor`(for docker user), paste output here 
docker run in container
wechaty-puppet-padchat@0.9.16

### Issue detail
```typescript
const announce = await keyroom.announce()
console.log(announce)
```
Try to get room announce but get undefined. 

### Full Output Logs

```shell
$ docker create -t -i --name=$docker_name \
--mount type=bind,source="${dir}",target=/bot \
-e WECHATY_LOG=silly \
-e TZ="America/Los_Angeles" \
zixia/wechaty:latest mybot.ts
$ docker start -a $docker_name 
```

<details>
<summary>
Show Logs
</summary>

### Paste the full output logs here with `WECHATY_LOG=silly` set 

```shell
# PASTE FULL LOG OUTPUT AT HERE:
08:50:04 VERB Room announce()
08:50:04 VERB PuppetPadchat roomAnnounce(12345@chatroom, )
08:50:04 SILL PadchatRpc rpcCall(WXGetChatroomAnnouncement, ["12345@chatroom"])
08:50:04 ERR PadchatRpc unexpected api call: WXGetChatroomAnnouncement
08:50:04 SILL PadchatRpc WXGetChatroomAnnouncement ,result: undefined
</details>

**Comment by windmemory** [comment]
With some investigation, currently get room announcement is not available in protocol level.

**Comment by windmemory** [comment]
Suppressed the error with: 9a53a05f7ee5ef22292511aba1e1a235041d04c7
