### ISSUE TITLE
Build failed, caused by tslint error on scanning cuid module.

### ISSUE THREAD

**Issue by windmemory** [lijiarui/wechaty-puppet-padchat#153]
```shell
14.55s$ npm test
> wechaty-puppet-padchat@0.9.29 test /home/travis/build/lijiarui/wechaty-puppet-padchat
> npm run lint && npm run test:unit && npm run test:int
> wechaty-puppet-padchat@0.9.29 lint /home/travis/build/lijiarui/wechaty-puppet-padchat
> npm run lint:ts && npm run lint:md
> wechaty-puppet-padchat@0.9.29 lint:ts /home/travis/build/lijiarui/wechaty-puppet-padchat
> tslint --project tsconfig.json && tsc --noEmit
node_modules/cuid/index.d.ts(15,13): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/cuid/index.d.ts(21,13): error TS7006: Parameter 'string' implicitly has an 'any' type.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechaty-puppet-padchat@0.9.29 lint:ts: `tslint --project tsconfig.json && tsc --noEmit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wechaty-puppet-padchat@0.9.29 lint:ts script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-08-15T06_21_25_309Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! wechaty-puppet-padchat@0.9.29 lint: `npm run lint:ts && npm run lint:md`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the wechaty-puppet-padchat@0.9.29 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-08-15T06_21_26_083Z-debug.log
npm ERR! Test failed.  See above for more details.
```

@zixia Do you know why tslint is scanning the `node_modules` folder? This error was never thrown out before, and theoretically `node_modules` folder should not be scanned by `tslint`. Is there any config that I am missing?

**Comment by zixia** [comment]
Please don't assign any issue to me unless you paid me (or donated to wechaty project) ;p

I remembered that the repository could be able to pass the CI before, can you check the difference between the passed and failed version? I believe it should helps.

**Comment by windmemory** [comment]
I checked back to the previous passed version, and run the `npm run test` command, failed with same error. 

I did some investigation after I created this issue, seems like the `//tslint:disable` is not working now. Don't know the reason, maybe it's something else, but if I didn't include the file that import `cuid`, everything is fine.

**Comment by zixia** [comment]
Have you solved your issue?

What's the problem caused this? I suggest you can share your experience under the issue to help others in the future. Thanks!

**Comment by windmemory** [comment]
I suppressed the typescript build on the `/example/raw-bot.ts` file since that file is neither a test nor a functional file.
