### ISSUE TITLE
⚠️  v0.15.2 - Potential broken

### ISSUE THREAD

**Issue by windmemory** [lijiarui/wechaty-puppet-padchat#158]
### DL;DR 
Message sent by yourself will be emitted in `message` event, if you didn't deal with the logic with self sent message, then your bot might be broken in this version.

---
### `v0.15.2`
Hi, please be careful upgrade your `wechaty-puppet-padchat` version to `v0.15.2` or above. From this version, `wechaty-puppet-padchat` will 'replay' the message sent by self. 

For previous versions, message sent by self via `wechaty-puppet-padchat` will not be emitted in `message` event, but from `v0.15.2`, the message will also be fired in the event. This change is making `wechaty-puppet-padchat` be align with other puppets, since the other puppets are emitting messages. 

### What do you need to do with the new version?
If your bot is listening on `message` event, then you need to be aware of whether the events is triggered by yourself, to avoid infinite loop message to yourself. You could refer to the code below:
```javascript
bot.on('message', function(message) {
  if (message.from().self()) {
    console.log('This message is from yourself')
  } else {
    //You can put your previous message logic here
  }
}
```

**Comment by kis87988** [comment]
This should be reasonable right? because the message send out should be get in the Pad as well. 
It will be similar to the earlier web version of Wechaty.

**Comment by windmemory** [comment]
@kis87988 Yes you are right. This is reasonable, but the iPad protocol is different from the web, so these messages are not automatically triggered. So I need to put extra logic to trigger that.

**Comment by kis87988** [comment]
Not only Message. 
I just realized the room-invite event will trigger if bot send to a contact. 
bot will also receive a room-invite.
