### ISSUE TITLE
change robot name success, but get robot info not fresh

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#161]
![image](https://user-images.githubusercontent.com/16509241/44513684-98293780-a6f0-11e8-9760-17be604618f7.png)

![image](https://user-images.githubusercontent.com/16509241/44513687-99f2fb00-a6f0-11e8-9cf0-5d274680d509.png)

**Comment by windmemory** [comment]
Need to update `wechaty` and `wechaty-puppet-padchat` to fix this issue. 
Changes for `wechaty-puppet-padchat` has been commited: https://github.com/lijiarui/wechaty-puppet-padchat/commit/96e2b54e6c17cdb93050268e83d3d0bf1c41f9f1
Changes for `wechaty` is waiting for review: https://github.com/Chatie/wechaty/issues/1576
