### ISSUE TITLE
puppet is not logged-in . WARN PuppetPadchat logout() this.id not exist

### ISSUE THREAD

**Issue by QinYuanyuan** [lijiarui/wechaty-puppet-padchat#165]
由于在 bot 上线之后，经常出现下面的 bug：
![image](https://user-images.githubusercontent.com/21057609/44831303-80096900-ac58-11e8-9e19-577c666bc541.png)

然后咨询之后，说是网络问题，建议在 wechaty 初始化的时候添加 profile 参数，并且使用 pm2 管理 bot。
但是在添加 profile 参数之后，再次上线 bot 。第一次扫码登录的时候，手机上显示 “ipad微信已登录“，但是 bot 没有任何反应，并且报错：
`puppet is not logged-in`
`WARN PuppetPadchat logout() this.id not exist`
![image](https://user-images.githubusercontent.com/21057609/44831417-0920a000-ac59-11e8-9abb-0f0cecb4ac01.png)

然后尝试在本地进行复现，又出现了一个新的已知的 bug ，这个同样是在添加 profile 参数之后出现的：
![image](https://user-images.githubusercontent.com/21057609/44831519-821ff780-ac59-11e8-97ce-07c8df979c1d.png)

我的 bot 代码：
```javascript
// 1. Declare your Bot!
const bot = new Wechaty({
  profile: 'alechat',
  puppet,
  puppetOptions,
})

// 2. Register event handlers for Bot
bot
 .on('logout', onLogout)
 .on('login', onLogin)
 .on('scan', onScan)
 .on('error', onError)
 .on('message', onMessage)
 .on('room-invite', onRoomInvite)
 .on('friendship', onFriendship)
```
如果 debug 需要更多的代码，请回复。希望可以尽快解决这些 bug。

**Comment by windmemory** [comment]
麻烦提供更多的代码吧，所有与`bot`这个变量相关的代码都麻烦贴一下

**Comment by windmemory** [comment]
我们这边需要可复现的代码或者更详细的log，请麻烦下次再出现这个问题的时候，把详细log贴一下给我们

**Comment by windmemory** [comment]
好的，谢谢了，那这个issue先关闭了哈，之后如果再次出现了，麻烦reopen这个issue，然后提供一下详细的log。
