### ISSUE TITLE
Module compatibility issue

### ISSUE THREAD

**Issue by g7rhythm** [lijiarui/wechaty-puppet-padchat#175]
current version:
  "wechaty": "^0.23.9",
    "wechaty-puppet-puppeteer": "^0.14.2"

Problem descrition：

when I install "tuling123-client" module , i found the puppet-padchat was error. 
the log msg was:"discarded message because puppet is not logged-in"
becase puppet is not logged-in so every functions was failed.

tuling123-client version is 0.0.3

pls check this out,thx~

**Comment by kis87988** [comment]
try to remove wechaty-puppet-puppeteer and install latest version of wechaty-puppet-padchat@next. 
if the issue still there, please put note on in the issue.

**Comment by lijiarui** [comment]
please move this to https://github.com/chatie/wechaty-puppet-puppeteer/issues

I will close this issue because this is not related to this one.
