### ISSUE TITLE
How to apply padchat token?

### ISSUE THREAD

**Issue by tianshunjian** [lijiarui/wechaty-puppet-padchat#178]
In [#1296](https://github.com/Chatie/wechaty/issues/1296) , @zixia says that "apply padchat token at [BotOrange.com](http://www.botorange.com/)". But there is only the introduction of "小桔机器人".

**Comment by lijiarui** [comment]
Anyone who want apply padchat token, please scan the following qrcode to contact the botorange:

![image](https://user-images.githubusercontent.com/6419514/45479213-6f88e080-b778-11e8-87f5-b69e8e4bae11.png)

**Comment by dyw934854565** [comment]
我以为这个账号会是机器人，自动同意然后发送padchat token

**Comment by lijiarui** [comment]
@dyw934854565 This can send you padchat token.
