### ISSUE TITLE
bot  在正常运行的过程中总是出现 WebSocket is not open: readyState 3 (CLOSED)

### ISSUE THREAD

**Issue by QinYuanyuan** [lijiarui/wechaty-puppet-padchat#183]
### 1. Expected behavior
**希望可以有一个方法判断 bot 是在connect状态还是在not connect状态**

**自己可以判断 bot 是否处于 not connect 的状态，如果是处于 not connect 的状态，这时就不要再对 bot 进行相关的操作，避免报 WebSocket is not open: readyState 3 (CLOSED) 这样的错误造成 bot 退出然后再次登录**

### 2. Actual behavior
**bot 会有掉线的时候，然后会自己进行 reconnect，但是在 reconnect的过程中我去对 bot 进行操作时，就会报下面的错误：**
![image](https://user-images.githubusercontent.com/21057609/46001021-d72a1e80-c0dc-11e8-902b-fb4cdb58c24e.png)

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**复现该问题的步骤就是当 bot 在执行reconnect() 时，对 bot 进行操作，如：room.say(content)**

### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by lijiarui** [comment]
请按照issue 模板，填写相关内容，包括浮现步骤，和详细的日志文件 :)

**Comment by QinYuanyuan** [comment]
按照 issue 的模板改好了，请帮忙看一下这个问题，由于 -106 的问题，测试环境的 bot 不能启动，所以没有打印详细的 log。

**Comment by QinYuanyuan** [comment]
目前这个问题发生的还是挺频繁的  之前我们的bot是两天掉一次线，现在有这个问题的原因，基本上每天掉线然后重新login七八次

**Comment by lijiarui** [comment]
-106 问题已经修复，这个问题可以通过自动重启，断线重连机器人的方式保证稳定运行。如果有更多的问题，欢迎提新的issue。这个issue 先关掉了。
