### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by yph152** [lijiarui/wechaty-puppet-padchat#186]
### 0. Report Issue Guide

Please search in the issue first, and make sure your problem had not been reported before.

### 1. Expected behavior

**Question: What behavior do you expect?**

Answer:

my code is as follows:
```
const bot = new Wechaty({
  puppet,
  puppetOptions,
})

bot.on('scan',onScan)
console.log('scan')
bot.on('login',onLogin)
console.log('login')
bot.on('message',onMessage)
console.log('message')
bot.start()

function onScan (qrcode, status) {
    const qrcodeImageUrl = [
      'https://api.qrserver.com/v1/create-qr-code/?data=',
      encodeURIComponent(qrcode),
    ].join('')
    console.log(qrcodeImageUrl)
}

function onLogin (user) {
    console.log(`${user} login`)
}
  
function onLogout(user) {
    console.log(`${user} logout`)
}
  
async function onMessage (msg) {
    console.log(msg.toString())
}
```

when I went to login，it's the following and no  information:

```
16:05:17 INFO Wechaty <wechaty-puppet-padchat> start() v0.22.4 is starting...
16:05:18 WARN PuppetPadchatManager startCheckScan() unknown WXCheckQRCodeStatus: -2
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FAc-3i2ncYwKZQl4NTgX3
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FAc-3i2ncYwKZQl4NTgX3
https://api.qrserver.com/v1/create-qr-code/?data=http%3A%2F%2Fweixin.qq.com%2Fx%2FAc-3i2ncYwKZQl4NTgX3
16:05:57 WARN PadchatRpc WXQRCodeLogin, redirect 301
```

### 2. Actual behavior

**Question: What actual behavior did you experience?**

Answer:

### 3. Steps to reproduce your problem (and fixes, if any)

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

**Question: What're the reproducible steps for us to see your problem?**

Answer:

### 4. Full Output Logs

<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

**Comment by kis87988** [comment]
Refer to: https://github.com/lijiarui/wechaty-puppet-padchat/issues/176
duplicate issue
