### ISSUE TITLE
Error ocurred when trying to log in by QRCode

### ISSUE THREAD

**Issue by tangxinyao** [lijiarui/wechaty-puppet-padchat#188]
I. Environment

-   macOS 10.13.6
-   nodejs 8.10.0
-   wechaty ^0.22.4
-   wechaty-puppet-padchat ^0.16.2

II.Description

  Hello guys I'm new to this project, and some problems happened to me today when I try to use this plugin to **log in** my wechat account by **QRCode**. Could anybody come to help solve this problem?
  
II.Error Stack

```
11:16:35 SILL PadchatRpc initWebSocket() ws.on(message): {"apiName":"WXQRCodeLogin","data":"%7B%22email%22%3A%22%22%2C%22external%22%3A%22%22%2C%22long_link_
11:16:35 ERR Config ###########################
11:16:35 ERR Config unhandledRejection: Error: PadchatRpc, WXQRCodeLogin, unknown status: -106 [object Promise]
11:16:35 ERR Config ###########################
11:16:35 ERR Config process.on(unhandledRejection) promise.catch(PadchatRpc, WXQRCodeLogin, unknown status: -106)
Config Error: PadchatRpc, WXQRCodeLogin, unknown status: -106
    at PadchatManager.<anonymous> (/Users/xinyaotang/workspace/lianyou-robot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:928:19)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xinyaotang/workspace/lianyou-robot/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

**Comment by lijiarui** [comment]
We had a workaround patch, see https://github.com/botorange/puppet-padchat-patch

Attention:
1. Please make sure you `wechaty-puppet-padchat` version is `v0.17.15` or later to use this patch.
2. Using this patch may cause wechat account block.

**Comment by lijiarui** [comment]
`-106` issue has been fixed. Update the latest code and have a try! I will close this issue then.
