### ISSUE TITLE
message回调收到位置信息报错，无法catch

### ISSUE THREAD

**Issue by CherryBoomBoom** [lijiarui/wechaty-puppet-padchat#203]
0. Report Issue Guide
Please search in the issue first, and make sure your problem had not been reported before.

1. Provide Your Package Version
What is your wechaty version?
Answer: "wechaty": "^0.22.4",

What is your wechaty-puppet-padchat version?
Answer: "wechaty-puppet-padchat": "^0.16.2"

2. Expected behavior
Question: What behavior do you expect?

Answer: 接受到位置信息的时候爆出错误，无法catch

3. Actual behavior
Question: What actual behavior did you experience?

Answer: 我发现在我的包里，位置是 wechaty-puppet-padchat\dist\src\pure-function-helpers\message-type.js 40行左右
没有定义Location的type，导致一收到位置message就报错，是否我的包不完整或者能否修复他。
4. Steps to reproduce your problem (and fixes, if any)
This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

Question: What're the reproducible steps for us to see your problem?

Answer: 

5. Full Output Logs
 Show Logs
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

**Comment by windmemory** [comment]
Thanks for the analysis and the helpful issue!

**Comment by windmemory** [comment]
Please update `wechaty-puppet-padchat` to `v0.17.21` or above to get the fix.
