### ISSUE TITLE
Some messages to room are missed

### ISSUE THREAD

**Issue by n1ro0** [lijiarui/wechaty-puppet-padchat#213]
### Some messages to room are missed, approximately 10%

1. We have following code：
```
for (let message of messages) {
    if (isFirst) {
        isFirst = false;
        await rooms[0].say(message, user);
    }
    else {
        await rooms[0].say(message);
     }
     await delay(500);
     console.log("Message sent(after await of say): ", message)
```

2. Here our log, where first message was sent and second not(without any log exception):

- 2018-11-15 09:59:53.000 EET:
`content: <msg><appmsg appid="" sdkver="0"><title>Logistics Director, China</title><des>Shanghai, €143K</des><username></username><action>view</action><type>5</type><showtype>0</showtype><url>https://staging.t20t.co/candidates/pphf-043284/logistics-director-china?token_key=e358f98c7b0933169cdea09c83c7ecd8b5229e71</url><contentattr>0</contentattr></appmsg></msg>`
- 2018-11-15 09:59:54.000 EET:
`Message sent(after await of say): UrlLink {payload: { description: 'Shanghai, €143K', thumbnailUrl: '', title: title: 'Logistics Director, China', url: 'https://staging.t20t.co/candidates/pphf-043284/logistics-director-china?token_key=********' } }`
- 2018-11-15 09:59:55.000 EET:
`Message sent(after await of say): UrlLink {payload: { description: 'Shanghai, €42.2K', thumbnailUrl: '', title: 'DBA', url: 'https://staging.t20t.co/candidates/cb056d44/dba?token_key=************' } }`

3. As we see from log second message was missed:
there is no log from `await rooms[0].say(message);` for second url message and it didn't throw any exception as our code `console.log("Message sent(after await of say): ", message)` logged message

**Comment by windmemory** [comment]
What kind of message are you trying to send?

Could you please try to increase the delay between messages and see the problem still exists?

**Comment by n1ro0** [comment]
I'll try, from logs u can see that two UrlLink messages were sent(payload is visiable in log above too)

**Comment by lijiarui** [comment]
@n1ro0 Could you give a more detailed info? Or we cannot help you to figure out the problem, thanks!

**Comment by windmemory** [comment]
Close this issue since no response for a month.
