### ISSUE TITLE
Error: Can not add user wxid_pjhau6yXXXX, this contactId is not searchable.

### ISSUE THREAD

**Issue by ipusi** [lijiarui/wechaty-puppet-padchat#219]
### 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://wechaty.botorange.com/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

### 1. 提供你的包版本信息
Where is the location of your server? (i.e. City, or In/Out China)
Xi'an
Which cloud platform(AliYun/Qcloud/DigitalOcean/etc) are you using?
local dev env

docker zixia/wechaty
  1. Wechaty version: 0.23.28
  2. Linux x64 version 4.9.93-linuxkit-aufs memory 157/1998 MB
  3. Docker: true
  4. Node version: v10.14.1
  5. Tcp IPC TEST: PASS
### 2. 期待程序运行的结果
添加群成员
### 3. 程序实际运行的结果
(node:38) UnhandledPromiseRejectionWarning: Error: Can not add user wxid_pjhau6ynena612, this contactId is not searchable. Please refer to issue: https://github.com/lijiarui/wechaty-puppet-padchat/issues/166
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1495:13)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:23:65)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:38) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:38) UnhandledPromiseRejectionWarning: Error: Can not add user wxid_j0ud9v2l8uyg12, this contactId is not searchable. Please refer to issue: https://github.com/lijiarui/wechaty-puppet-padchat/issues/166
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1495:13)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:23:65)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:38) UnhandledPromiseRejectionWarning: Error: Can not add user wxid_1u1v95qex1qg12, this contactId is not searchable. Please refer to issue: https://github.com/lijiarui/wechaty-puppet-padchat/issues/166
    at PuppetPadchat.<anonymous> (/wechaty/node_modules/wechaty-puppet-padchat/src/puppet-padchat.ts:1495:13)
    at Generator.throw (<anonymous>)
    at rejected (/wechaty/node_modules/wechaty-puppet-padchat/dist/src/puppet-padchat.js:23:65)
(node:38) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
^CERROR: Bot exited with code 1
### 4. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
- 第一步：登陆
- 第二步：扫描群成员，发送添加请求
- 。。。

### 5. 完整的日志信息：
**请提供完整的日志信息(不要只提供部分的日志内容！)**
<details>
<summary>
Show Logs
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

**Comment by lijiarui** [comment]
This may fixed by [wechaty-puppet-padpro](https://github.com/botorange/wechaty-puppet-padpro)

**Comment by windmemory** [comment]
Duplicate with https://github.com/lijiarui/wechaty-puppet-padchat/issues/166
