### ISSUE TITLE
图片/视频发送不成功

### ISSUE THREAD

**Issue by yukunmu** [lijiarui/wechaty-puppet-padchat#220]
### 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://wechaty.botorange.com/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

### 1. 提供你的包版本信息
- wechaty 版本：0.22.1
- wechaty-puppet-padchat 版本：0.18.1
- node 版本：v10.14.1 (运行 `node --version` 获取版本)

### 2. 期待程序运行的结果
3个群聊，群名分表为：收收收、发发发1、发发发2
“收收收”接收到的群消息，分发至“发发发1”、“发发发2”

### 3. 程序实际运行的结果
可以正常收发文字、语音消息，图片、视频消息接收后无回调，或者转发送时报错

[收收收]<余坤牧>:Message#Image(👥Room<收收收>🗣Contact<余坤牧>)
queryRules => [{"state":"on","start":"2018-12-09 00:00:00","end":"2018-12-11 00:00:00","origin":"收收收","targets":["发发发1","发发发2"],"speakers":["余坤牧","K"]},{"state":"on","start":"2018-12-09 00:00:00","end":"2018-12-11 00:00:00","origin":"往这发（主讲）","targets":["分享组1","分享组2"],"speakers":["余坤牧"]}]
repost to room(topic: 发发发1).
20:45:30 WARN PuppetPadchat messageFile(98501023694943778)
Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/root/wechaty-getting-started/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1332:23)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechaty-getting-started/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

![image](https://user-images.githubusercontent.com/35764653/49733937-cccff780-fcbd-11e8-997e-06179da60fbc.png)
![image](https://user-images.githubusercontent.com/35764653/49733957-dbb6aa00-fcbd-11e8-9bcc-f23d8face302.png)
![image](https://user-images.githubusercontent.com/35764653/49733971-e1ac8b00-fcbd-11e8-892f-cfdb426b6c5a.png)

### 4. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
- 第一步：建3个群聊（A、B、C）
- 第二步：A群收到的消息发送到B、C
- 第三步：往A群发送图片或视频
- 。。。

### 5. 完整的日志信息：
**请提供完整的日志信息(不要只提供部分的日志内容！)**
<details>
<summary>
[收收收]<余坤牧>:Message#Unknown(👥Room<收收收>🗣Contact<余坤牧>)<<msg>
<op id='2'>
<username>4298789575@chatroom</username>
</op>
</msg>
[收收收]<余坤牧>:Message#Image(👥Room<收收收>🗣Contact<余坤牧>)
queryRules => [{"state":"on","start":"2018-12-09 00:00:00","end":"2018-12-11 00:00:00","origin":"收收收","targets":["发发发1","发发发2"],"speakers":["余坤牧","K"]},{"state":"on","start":"2018-12-09 00:00:00","end":"2018-12-11 00:00:00","origin":"往这发（主讲）","targets":["分享组1","分享组2"],"speakers":["余坤牧"]}]
repost to room(topic: 发发发1).
20:45:30 WARN PuppetPadchat messageFile(98501023694943778)
Error: WXGetMsgImage , stranger,error! canot get result from websocket server
    at PadchatManager.<anonymous> (/root/wechaty-getting-started/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:1332:23)
    at Generator.next (<anonymous>)
    at fulfilled (/root/wechaty-getting-started/node_modules/wechaty-puppet-padchat/dist/src/padchat-rpc.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
^Croot@instance-7w060fob:~/wechaty-getting-started# 
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

```

</details>

**Comment by yukunmu** [comment]
估计是文件大小的问题，试过用100KB左右的图可以发成功，1M左右的则不行

**Comment by windmemory** [comment]
图片太大会导致无法发送，这个是目前`wechaty-puppet-padchat`已知的限制。

目前视频的收发在`wechaty-puppet-padchat` 里面不支持

如果有需要，请看一下[`wechaty-puppet-padpro`](https://github.com/botorange/wechaty-puppet-padpro)
