### ISSUE TITLE
登录状态自动断开

### ISSUE THREAD

**Issue by august741** [lijiarui/wechaty-puppet-padchat#229]
### 0. 发 Issue 指南

1. 请运行下面的命令，看问题是否可以被解决：
```
rm -rf package-lock.json
rm -rf node_modules
npm install
```

2. 请在 [FAQ 清单](https://docs.chatie.io/v/zh/faq) 看是否已有解决办法。

3. 请先在issue 中搜关键信息，确认你要发的内容和之前的issue 不重复。

### 1. 提供你的包版本信息
- wechaty 版本：
- wechaty-puppet-padchat 版本：
- node 版本：v10.15.0

### 2. 期待程序运行的结果
能够长时间 稳定的连接 不会每天都出现断连情况（这样需要重新登录）
### 3. 程序实际运行的结果

![image](https://user-images.githubusercontent.com/46594096/51026051-a0631000-15c8-11e9-8ed2-6452c6f6a202.png)

### 4. 复现的步骤 (或者解决的步骤)

**这一部分非常重要，如果你无法给出复现步骤，我们也很难提供相应的解决办法：**
例子:
pad 接入
```
bot
    .on('scan', (url, code) => {
        let loginUrl = url.replace('qrcode', 'l')
        require('qrcode-terminal').generate(loginUrl)
        console.log(url)
    })
    .on('logout', user => log.info('Bot', `"${user.name()}" logouted`))
    .on('error', e => log.info('Bot', 'error: %s', e))

    .on('login', async function (user) {
        let msg = `${user.name()} logined`
        log.info('Bot', msg)
        await this.say(msg)
    })




    /**
     * Global Event: message
     */
    .on('message', async function (msg) {
        if (msg.age() > 3 * 60) {
            log.info('Bot', 'on(message) skip age("%d") > 3 * 60 seconds: "%s"', msg.age(), msg)
            return
        }

        const room = msg.room()
        const from = msg.from()
        const text = msg.text()

        if (!from) {
            return
        }

        var from_id = from.id
        var mention = await msg.mention()
        if (msg.self()) {
            return // skip self
        }
        var room_id = '';
        try {
            room_id = room.id;
        } catch (e) {
            console.log('id error:', e);
        }
    })
    .start()
    .catch(e => console.error(e))
```

### 5. 完整的日志信息：
**请提供完整的日志信息(不要只提供部分的日志截图，请复制粘贴日志内容！)**
日志没有报错 直接出现
WARN PadchatRpc initWebSocket() ws.on(close) code:1005 .reason:

**Comment by windmemory** [comment]
麻烦提供一下`bot`的创建的代码

**Comment by august741** [comment]
#!/usr/bin/env node
const {
    config,
    Contact,
    Room,
    Wechaty,
    log,
} = require('wechaty')

const WECHATY_PUPPET_PADCHAT_TOKEN = ''

const puppet = 'wechaty-puppet-padchat' // 使用ipad 的方式接入。

const puppetOptions = {
    token: WECHATY_PUPPET_PADCHAT_TOKEN,
}

const bot = new Wechaty({
    puppet,
    puppetOptions,
})

**Comment by windmemory** [comment]
Please refer to https://docs.chatie.io/v/zh/faq#login-status-persistent
