### ISSUE TITLE
撤回消息功能的支持

### ISSUE THREAD

**Issue by geniusun** [lijiarui/wechaty-puppet-padchat#257]
> 重要：请不要删除模板自行填写，所有不按照模板填写的issue，我们将不会处理。

**描述这个功能的缺失带来的问题**
请用精简的语言描述你遇到的问题，如：当遇到 [...] 的时候，我会 [...]
Bot在群里发现用户发送的消息撤回。当机器人捕捉不到撤回时，会无法验证用户完成我们的奖励任务。
**描述你期待的解决方案**
Bot可以获取到撤回类消息的消息类型，并且里面包含撤回消息的id

**描述你考虑过的备选方案**
无

**其他信息**
和此新功能相关的其他描述或截图。

[enhancement]

**Comment by windmemory** [comment]
撤回消息已经在`wechaty-puppet-padpro`里面支持，如果对此有需求，请迁移至`wechaty-puppet-padpro`
