### ISSUE TITLE
room-bot test

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#63]
- manageDingRoom (DingRoom means room topic begin with `ding`, monitor `ding` room join/leave/topic event)
     - [x] room.on('join') 
         - [x] get log: `log.verbose('Bot', 'Room EVENT: join - %s, %s' ) `
         - [x] checkRoomJoin.call()
     - [x] room.on('leave'): get log `'Room EVENT: leave - %s leave(remover %s), byebye`
     - [x] room.on('topic'): get log `Room EVENT: topic - changed from %s to %s by member %s`
--------
- checkRoomJoin.call()
  -  bot invite other
     - [x] room.say('Welcome to my room! :)')
     - [x] change topic name to `ding-welcome-` + `inviteeList.map(c => c.name()).join(', ')`
  -  other invite other
     - [x] room.say('RULE1: Invitation is limited to me, the owner only. Please do not invit people without notify me.', inviter)
     - [x] room.say('Please contact me: by send "ding" to me, I will re-send you a invitation. Now I will remove you out, sorry.',inviteeList)
     - [x] change topic name to `ding-warn` + `inviter.name()`
     - delete intitee from the room after 10 seconds
         - [x] remove contact from the room
         - [x] cannot get leaver name: https://github.com/Chatie/wechaty/issues/1329

----------

-  room-join event
   - [x] get log `EVENT: room-join - Room %s got new member %s, invited by %s`
   - [x] room.say(`welcome to ${topic}!`, inviteeList[0])
-  room-leave event
   - [x] get log `EVENT: room-leave - Room %s lost member %s`
   - [x] room.say(`kick off ${name} from ${topic}!` ) Chatie/wechaty#1329
- room-topic event
   - [x] get log `EVENT: room-topic - Room %s change topic from %s to %s by member %s`
   - [x] room.say(`room-topic - change topic from ${oldTopic} to ${topic} by member ${changer.name()}` )

**Comment by lijiarui** [comment]
--------
- send `ding` to bot peer to peer 
   - `ding` room exist
      - [ ] get log: `log.info('Bot', 'onMessage: got dingRoom: %s', dingRoom.topic())`
        - sender in `ding` room
          - [ ] get log:`log.info('Bot', 'onMessage: sender has already in dingRoom')`
          - [ ] dingRoom.say('no need to ding again, because you are already in ding room')
        - sender not in `ding` room
          - [ ] get log: `log.info('Bot', 'onMessage: add sender(%s) to dingRoom(%s)', from.name(), dingRoom.topic())`
          - [ ] from.say('ok, I will put you in ding room!')
          - [ ] room.add(from)
          - [ ] room.say('Welcome ', from),
   - `ding` room not exsite
        - [ ] createDingRoom(contact)
           - [ ] room.topic('ding - created')
           - [ ] room.say('ding - created')
        - [ ]  manageDingRoom
----------------------

- send `ding` to bot in `ding` room
   - [ ] room.say('You said "ding" in my room, I will remove you out.')
   - [ ] room.del(contact)

**Comment by lijiarui** [comment]
done! 👍

**Comment by zixia** [comment]
Congratulations!
