### ISSUE TITLE
WXGetChatRoomMember() result: {"message": "WS请求错误", "statue": -19}

### ISSUE THREAD

**Issue by lijiarui** [lijiarui/wechaty-puppet-padchat#64]
This may because the room Id is invalid(long time not activate...)

Solution：
The valid and invalid room Id can be recognized in `WXSyncContact`, so we should deal data here.

**Comment by zixia** [comment]
That makes sense: chatroom id expired.

It could also be related with the room search functionality: When bot was removed out from a chat room, the bot should treat that room as not exist. But in our current code, the room id is still in the cache store, and the bot can still find it out and do not know that room id is expired.

Need to be fixed.

**Comment by lijiarui** [comment]
for more detail info: 
For `苏轼` account：
valid chatroomid:  8314006917@chatroom
invalid chatroomid:  6930884171@chatroom

more log as follows:

![wechatimg19](https://user-images.githubusercontent.com/6419514/41418970-8190eb20-7023-11e8-863d-caf90cdde9ad.jpeg)

**Comment by zixia** [comment]
The new code will remove the cache owned by those roomId whose `status:-19`
