### ISSUE TITLE
Chatie/wechaty/issues Multiple WXInitialize info but no QR code received

### ISSUE THREAD

**Issue by qhduan** [lijiarui/wechaty-puppet-padchat#68]
![931466380](https://user-images.githubusercontent.com/3895924/41636007-7bd4f85c-747e-11e8-9a1a-902b450cb21a.jpg)

Suggestion:
Puppet check itself if it login fail too many times. Then to send a warning to padchat server (may be a webhook), let padchat server could restart itself

**Comment by lijiarui** [comment]
@zixia How do you think about it.

in `src/puppet-padchat/padchat-rpc.ts` 

```diff
  public async start(): Promise<void> {
    log.verbose('PadchatRpc', 'start()')

    await this.initWebSocket()
    await this.initJsonRpc()

    this.startQueues()

    await this.init()
 +   await this.WXInitialize()
```

**Comment by zixia** [comment]
I cannot help without any minimum reproducible code.

**Comment by lijiarui** [comment]
fix by awei by restart everyday by timer
