### ISSUE TITLE
Needs to mock padchat-manager inside puppet-padchat

### ISSUE THREAD

**Issue by windmemory** [lijiarui/wechaty-puppet-padchat#86]
I would like to know how to mock the private property `padchat-manager` inside `puppet-padchat`. And I would like to only mock one method on `padchat-manager`, which is the `WXGetContactPayload`. 

Do you know any way to do this?

**Comment by zixia** [comment]
It's very easy.

Please see my PR, and feel free to let me know if you have any questions.

**Comment by windmemory** [comment]
Close this issue since the problem is solved.
