### ISSUE TITLE
Enable greenkeeper

### ISSUE THREAD

**Issue by zixia** [lijiarui/wechaty-puppet-padchat#90]
Please enable the greenkeeper for this repository by visiting the https://greenkeeper.io and follow the instructions over there.

**Comment by zixia** [comment]
ping @windmemory

**Comment by windmemory** [comment]
@lijiarui Could you please install the `greenkeeper` first? Since the repository is under your personal account.

**Comment by windmemory** [comment]
fixed with https://github.com/lijiarui/wechaty-puppet-padchat/pull/172
