### ISSUE TITLE
首次登录时验证设备的问题

### ISSUE THREAD

**Issue by linxiaojialin** [lijiarui/wechaty-puppet-padchat#93]
请问首次登录时微信要求验证设备，需要怎么处理呢？能自己生成62吗？

**Comment by lijiarui** [comment]
这些wechaty 已经都处理好了，不需要你任何操作，具体请看文档： https://qhduan.github.io/wechaty-doc/#/zh

**Comment by zixia** [comment]
![image](https://user-images.githubusercontent.com/1361891/42640134-34b01648-8624-11e8-8b35-1e1457d3b300.png)

**Comment by lijiarui** [comment]
https://qhduan.github.io/wechaty-doc/#/zh/  sorry miss a   /     here

**Comment by linxiaojialin** [comment]
涉及到一个先有鸡还是先有蛋的问题。这个的应用场景是已登录（说明已生成62）的号扫码成为机器人；我想做应用场景是将账号密码写在配置文件中，就可以启动的（因为不止一个号，无法全部登录后一个个扫）。请问目前wechaty支持吗？或者有实现的思路吗？我可以参与完善功能

**Comment by lijiarui** [comment]
Sorry we do not have plan to support this.

**Comment by windmemory** [comment]
ping @lijiarui 

Can we close this issue? And please update the doc link above, seems they are out of date now.
