### ISSUE TITLE
获取群成员信息不完整

### ISSUE THREAD

**Issue by zhaokefei** [lijiarui/wechaty-puppet-padchat#98]
**目前获取群内成员的信息仅能获取到 成员的 wxid, 其余有关 头像、名称、性别、城市等信息无法获取到**

**Comment by windmemory** [comment]
目前群成员如果非好友，只能获取到头像，昵称和id，麻烦再确认一下这些信息是否完整。其他的信息目前的版本不支持。 @zhaokefei

**Comment by lijiarui** [comment]
ping @zhaokefei

**Comment by lijiarui** [comment]
I will close this issue since haven't heard any update for a long time
